version: 2
jobs:
  build:
    docker:
      - image: veton/dotscript
    steps:
      - checkout
      - run:
          name: Run Tests
          command: pwsh ./test/run.ps1
      - run:
          name: Publish to NPM
          command: pwsh ./build/publish-npm.ps1
      - run:
          name: Publish to NuGet
          command: pwsh ./build/publish-nuget.ps1
